module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    ADMIN_COLLECTION:'admin',
    CATEGORY_COLLECTON:'category',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    USERADDRESS_COLLECTION:'address',
    COUPON_COLLECTION:'coupon'
}